const myProducts = [
    {
        name: "Artemis Candle",
        price: "$120",
        image: "https://cdn.shopify.com/s/files/1/0471/0521/2567/products/Artemis_540x.jpg?v=1618314122",
        availQuantity: 100,
        variants: ["Unscented", "Vanilla scent", "Dry tobacco & hay scent"],
        featured: true,
        info: "Exclusively to Pretty Candles, the classical bust of the ancient Greek goddess Artemis has been thoughtfully curated for all to admire the rhythmic detail and natural draperies she possesses.",
        dimensions: "30 cm H x 17 cm W x 12.5 cm D",
    },
    {
        name: "Pillar Candle",
        price: "$99.95",
        image: "https://cdn.shopify.com/s/files/1/0471/0521/2567/products/IMG-5275_1024x1024@2x.jpg?v=1629357003",
        availQuantity: 90,
        variants: ["Unscented", "Vanilla scent", "Dry tobacco & hay scent"],
        featured: true,
        info: "Stylish pillar candle, suitable for home and dinner parties.",
        dimensions: "30cm L x 9cm W x 9 cm H",
    },
    {
        name: "Cube Candle",
        price: "$39.95",
        image: "https://cdn.shopify.com/s/files/1/0471/0521/2567/products/Destijl_1024x1024@2x.jpg?v=1618314176",
        availQuantity: 50,
        variants: ["Unscented", "Vanilla scent", "Dry tobacco & hay scent"],
        featured: false,
        info: "Inspired by a famous art movement from the twentieth century which advocated for pure abstraction through creating a reduction of the essential form and colour.",
        dimensions: "8 cm H x 8 cm W x 8 cm D ",
    },
    {
        name: "Earth Candle",
        price: "$39.95",
        image: "https://cdn.shopify.com/s/files/1/0471/0521/2567/products/IMG-3590_1024x1024@2x.jpg?v=1620904269",
        availQuantity: 50,
        variants: ["Unscented", "Vanilla scent", "Dry tobacco & hay scent"],
        featured: false,
        info: "Made from a sustainable beeswax blend. Australian made.",
        dimensions: "8.5cm H x 8.5 cm W ",
    },
    {
        name: "Grecian Amphora Candle",
        price: "$34.95",
        image: "https://cdn.shopify.com/s/files/1/0471/0521/2567/products/Amphora_1024x1024@2x.jpg?v=1618314286",
        availQuantity: 10,
        variants: ["Unscented", "Vanilla scent", "Dry tobacco & hay scent"],
        featured: true,
        info: "The Amphora candle is the perfect way to add a hint of Hellenism to your space. This piece of art is exclusive to Pretty Candles, as it is the first of its kind on the market.",
        dimensions: "11 cm H x 7 cm W x 7 cm D",
    },
    {
        name: "Swirl Candle",
        price: "$64.99",
        image: "https://cdn.shopify.com/s/files/1/0471/0521/2567/products/IMG-7873_1024x1024@2x.jpg?v=1644724209",
        availQuantity: 0,
        variants: ["Unscented", "Vanilla scent", "Dry tobacco & hay scent"],
        featured: true,
        info: "This candle is made for decorative use, however, if you decide to burn it, we strongly recommend you place a heat-proof dish under this product to help control any excess wax from dripping.",
        dimensions: "12cm H x 12 cm W",
    },
    {
        name: "The Infinity Knot Candle",
        price: "$49.99",
        image: "https://cdn.shopify.com/s/files/1/0471/0521/2567/products/IMG-2640_1024x1024@2x.jpg?v=1637754053",
        availQuantity: 100,
        variants: ["Unscented", "Vanilla scent", "Dry tobacco & hay scent"],
        featured: false,
        info: "The Infinity Knot candle is the new must have! Finally, a perfect gift idea for the minimalist in your life.",
        dimensions: "11cm W  x 8cm D x 13 cm H",
    },
    {
        name: "Grecian Column Candle",
        price: "$24.95",
        image: "https://cdn.shopify.com/s/files/1/0471/0521/2567/products/custom_resized_32f56bd0-bb14-4e51-bcfd-52a6506af98d_1024x1024@2x.jpg?v=1613563048",
        availQuantity: 100,
        variants: ["White", "Black"],
        featured: false,
        info: "A contemporary twist on ancient Greek architecture.",
        dimensions: "27 H x 3.5 cm W x 3.5 cm D",
    },
    {
        name: "Star Candle",
        price: "$85.00",
        image: "https://cdn.shopify.com/s/files/1/0471/0521/2567/products/IMG-9322_1024x1024@2x.jpg?v=1633315539",
        availQuantity: 100,
        variants: ["Unscented", "Vanilla scent", "Dry tobacco & hay scent"],
        featured: false,
        info: "Every candle is quality controlled and is unique given his hand-made nature, however, slight variations may occur between candles, adding to his one of a kind beauty.",
        dimensions: "32 cm H x 11 cm W",
    },
    {
        name: "Gemini Candle",
        price: "$49.00",
        image: "https://cdn.shopify.com/s/files/1/0471/0521/2567/products/image_6c6b26c2-a7c0-46af-a705-816dc867a38c_1024x1024@2x.jpg?v=1639393281",
        availQuantity: 0,
        variants: ["Unscented", "Vanilla scent", "Dry tobacco & hay scent"],
        featured: true,
        info: "Please note, every candle is unique given its hand-made nature; we check every candle before sending to ensure our quality standard, however slight variations may occur between candles.",
        dimensions: "20cm H  x 12cm W x 3 cm D",
    },
];

export default myProducts;
